name: Build Modules Package and Update Version

on:
  push:
    paths:
      - 'modules/**'
      - 'main.sh'
      - 'install.sh'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create modules tarball
        run: |
          tar -czvf modules.tar.gz modules/
      
      - name: Update version
        run: |
          # 获取当前日期作为版本号的一部分
          DATE=$(date +%Y%m%d)
          
          # 获取当天的提交次数
          COMMITS=$(git rev-list --count --since="00:00" HEAD)
          
          # 读取当前版本号的主要部分（如果存在）
          if [ -f "version.txt" ]; then
            CURRENT_VERSION=$(cat version.txt)
            MAJOR_MINOR=$(echo $CURRENT_VERSION | grep -oE "^[0-9]+\.[0-9]+")
            if [ -z "$MAJOR_MINOR" ]; then
              MAJOR_MINOR="1.0"
            fi
          else
            MAJOR_MINOR="1.0"
          fi
          
          # 生成新版本号 (例如: 1.0.20230815.2)
          NEW_VERSION="${MAJOR_MINOR}.${DATE}.${COMMITS}"
          
          # 更新version.txt (确保使用UTF-8编码，不带BOM)
          echo -n "$NEW_VERSION" > version.txt
          
          echo "版本已更新为: $NEW_VERSION"
      
      - name: Update repository
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add modules.tar.gz version.txt
          git commit -m "自动更新: modules.tar.gz 和版本号 $(cat version.txt)" || echo "无变更需要提交"
          git push 